# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  qdrant-vector-db:
    image: qdrant/qdrant
    container_name: qdrant-vector-db
    ports:
      - "6333:6333"
      - "6334:6334"
    healthcheck:
      test: curl -s http://localhost:6333/healthz | grep -q 'healthz check passed' || exit 1
      interval: 30s
      retries: 20
      start_period: 30s
