# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
<<<<<<< HEAD
  neo4j-apoc:
    image: neo4j:latest
    container_name: neo4j-apoc
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
    ipc: host
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
=======
  neo4j-db:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - "${NEO4J_PORT1:-7474}:7474"
      - "${NEO4J_PORT2:-7687}:7687"
    ipc: host
    environment:
>>>>>>> 528eacd0fa249acf708d06dddce78e78bdb5e4e8
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\*
<<<<<<< HEAD
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 3s
=======
    healthcheck:
      test: ["CMD-SHELL", "sleep 10 && exit 0"]
      interval: 1s
      timeout: 15s
      retries: 1
>>>>>>> 528eacd0fa249acf708d06dddce78e78bdb5e4e8
