# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3"
services:
  elasticsearch-vector-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch-vector-db
    ports:
      - "${ELASTICSEARCH_PORT:-12300}:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
    healthcheck:
      test: curl -s http://localhost:9200/_health_report | grep '"status":"green"'
      interval: 10s
      timeout: 5s
      retries: 5
