# Copyright (C) 2024 Prediction Guard, Inc
# SPDX-License-Identifier: Apache-2.0

services:
  embedding:
    image: ${REGISTRY:-opea}/embedding:${TAG:-latest}
    container_name: embedding
    ports:
      - ${EMBEDDER_PORT}:${EMBEDDER_PORT}
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      PG_EMBEDDING_MODEL_NAME: ${PG_EMBEDDING_MODEL_NAME}
      PREDICTIONGUARD_API_KEY: ${PREDICTIONGUARD_API_KEY}
      EMBEDDING_COMPONENT_NAME: "OPEA_PREDICTIONGUARD_EMBEDDING"
    restart: unless-stopped

networks:
  default:
    driver: bridge
