# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  multimodal-clip-embedding:
    image: opea/embedding-multimodal-clip:latest
    container_name: multimodal-clip-embedding-server
    ports:
      - "${MULTIMODAL_CLIP_EMBEDDER_PORT:-6990}:6990"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped

networks:
  default:
    driver: bridge
